# Workflow for building and deploying Next.js site to GitHub Pages
name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: 'yarn'
      - name: Clear Yarn Cache
        run: yarn cache clean
      - name: Delete node_modules and yarn.lock
        run: rm -rf node_modules yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build with Next.js
        run: yarn build
      - name: Static HTML export with Next.js
        run: yarn next export
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: next-build
          path: out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: 'yarn'
      - name: Debug Artifacts
        run: echo "Artifacts: ${{ toJson(needs.build.outputs.artifacts) }}"
        needs: build
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: next-build
          path: .
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2



